//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VerifyTenantConfiguration.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VerifyTenantConfiguration.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Do not Promote this Json to Production..
        /// </summary>
        internal static string DontPromoteToProd {
            get {
                return ResourceManager.GetString("DontPromoteToProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///Press any key to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ===============================================.
        /// </summary>
        internal static string Filler {
            get {
                return ResourceManager.GetString("Filler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposed PosConfiguration is Invalid Json Format.
        /// </summary>
        internal static string InvalidJsonFormat {
            get {
                return ResourceManager.GetString("InvalidJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///There is a descripency between production tenantids and tenantids of proposed Json file. Make sure following TenantId(s) are present in Json File. .
        /// </summary>
        internal static string MissingTenantIds {
            get {
                return ResourceManager.GetString("MissingTenantIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a mismatch of Tenant Count beteen Production data and proposed Json file..
        /// </summary>
        internal static string TenantIdCountMismatch {
            get {
                return ResourceManager.GetString("TenantIdCountMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Following TenantId(s) do not have programCodes configured in proposed json .
        /// </summary>
        internal static string TenantIdsMissingProgramCodes {
            get {
                return ResourceManager.GetString("TenantIdsMissingProgramCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Following TenantId(s) do not have programIds configured in proposed json.
        /// </summary>
        internal static string TenantIdsMissingProgramIds {
            get {
                return ResourceManager.GetString("TenantIdsMissingProgramIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///PosConfiguration validation is successful..
        /// </summary>
        internal static string ValidationSuccessful {
            get {
                return ResourceManager.GetString("ValidationSuccessful", resourceCulture);
            }
        }
    }
}
